GET http://localhost:3000

### SEND FETCH SONGS REQUEST
GET http://localhost:3000/songs/?page=1&limit=2

### Find SONGS REQUEST
GET http://localhost:3000/songs/1

### Create New SONGS REQUEST
POST http://localhost:3000/songs
Content-Type: application/json

{
"title": "New Song 5",
"artists": [
    "Siagla",
    "Martin",
    "John"
],
"releasedDate" : "2023-05-11",
"duration" :"02:34",
"lyrics": "Sby, you're my adrenaline. Brought out this other side of me You don't even know Controlling my whole anatomy, oh Fingers are holding you right at the edge You're slipping out of my hands Keeping my secrets all up in my head I'm scared that you won't want me back, oh I dance to every song like it's about ya I drink 'til I kiss someone who looks like ya I wish that I was honest when I had you I shoulda told you that I wanted you for me I dance to every song like it's about ya I drink 'til I kiss someone who looks like ya"
}


### Update SONGS REQUEST
PUT http://localhost:3000/songs/2
Content-Type: application/json

{
"title": "Animals",
"artists": [
    "Martin"
],
"releasedDate" : "2023-02-02",
"duration" :"03:43",
"lyrics": "ANIM, you're my adrenaline. Brought out this other side of me You don't even know Controlling my whole anatomy, oh Fingers are holding you right at the edge You're slipping out of my hands Keeping my secrets all up in my head I'm scared that you won't want me back, oh I dance to every song like it's about ya I drink 'til I kiss someone who looks like ya I wish that I was honest when I had you I shoulda told you that I wanted you for me I dance to every song like it's about ya I drink 'til I kiss someone who looks like ya"
}

### Update SONGS REQUEST
DELETE http://localhost:3000/songs/1